### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by OliviaOliveiira** [XmYx/deforum-comfy-nodes#2]
## Execute install/(de)activation script for 'C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes'
 Collecting basicsr==1.3.5
   Downloading basicsr-1.3.5.tar.gz (161 kB)
      ------------------------------------ 161.4/161.4 kB 744.4 kB/s eta 0:00:00
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'done'
 Requirement already satisfied: addict in c:\comfyui_blyat\comfyui_windows_portable_nvidia_cu121_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from basicsr==1.3.5) (2.4.0)
 Collecting future (from basicsr==1.3.5)
   Downloading future-0.18.3.tar.gz (840 kB)
      -------------------------------------- 840.9/840.9 kB 3.8 MB/s eta 0:00:00
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\USER01\AppData\Local\Temp\pip-install-4qdn0ljs\future_38f2d17a6881404ab51fc93aa7015518\setup.py", line 86, in <module>
[!]       import src.future
[!]   ModuleNotFoundError: No module named 'src'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes

**Comment by XmYx** [comment]
Issue is with the embedded python of your installation, suggested fix:

Install comfy from source in a venv created manually, then reinstall the node package.

**Comment by OliviaOliveiira** [comment]
Are you planning on making it comfy-portable friendly or..? Most users do use portable versions, so this might be a good idea (if there’s no restrictions to complete it)

**Comment by XmYx** [comment]
Sure, I'll look into it, but it's about installing basicsr and future in a venv, which is normally very straightforward, so the embedded python implementation has some issue. You can just recreate the venv in your portable comfy using windows's built in python, and keep using the same 'portable' version.

**Comment by OliviaOliveiira** [comment]
Will look into it, thanks.

**Comment by XmYx** [comment]
Reopening the issue to indicate that this was fixed by removing basicsr from the requirements, and by bumping pandas requirement version. You can now install Deforum Nodes to a portable ComfyUI installation as well.

**Comment by OliviaOliveiira** [comment]
Have you checked if it works? I've just uninstalled and installed once again via manager and here I am again with

Traceback (most recent call last):
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\__init__.py", line 1, in <module>
    from .deforum_nodes.deforum_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\deforum_node.py", line 34, in <module>
    from deforum import DeforumAnimationPipeline, ImageRNGNoise
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\deforum\__init__.py", line 4, in <module>
    from .generators import (ComfyDeforumGenerator,
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\deforum\generators\__init__.py", line 2, in <module>
    from .film_interp_generator import FILMInterpolator
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\deforum\generators\film_interp_generator.py", line 4, in <module>
    from ..models.FILM.inference import FilmModel
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\deforum\models\__init__.py", line 3, in <module>
    from .depth_models.depth import DepthModel
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\deforum\models\depth_models\depth.py", line 16, in <module>
    from .depth_midas import MidasDepth
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\deforum\models\depth_models\depth_midas.py", line 10, in <module>
    from ...utils.file_dl_util import download_file_with_checksum
  File "C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\deforum\utils\file_dl_util.py", line 6, in <module>
    from basicsr.utils.download_util import load_file_from_url
ModuleNotFoundError: No module named 'basicsr'

Cannot import C:\ComfyUI_BLYAT\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes module for custom nodes: No module named 'basicsr'

**Comment by XmYx** [comment]
Yes, the solution is to uninstall your deforum package from the portable virtual environment. I'll work on an uninstall/reinstall script that makes sure this purge happens, in the meanwhile you can navigate to your comfy_portable_folder/python_embeded/Lib/site-packages and delete both deforum and deforum-0.1.8.dev1.dist-info folders. Then click "Try fix" in ComfyUI Manager on Deforum Nodes. It should reinstall the backend requirement, not needing basicsr anymore, and also bumping the used pandas version to work woth python 3.11.

**Comment by OliviaOliveiira** [comment]
Thanks! It did work, will try to play with it now)
