### ISSUE TITLE
UnboundLocalError: cannot access local variable 'tmp_audio_file'

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [XmYx/deforum-comfy-nodes#23]
Hello you all trying to get these nodes working for a project.

I get this error

Anyone know what the issue could be

Moviepy - Done !
Moviepy - video ready Z:\R3P0S\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\output\Deforum_1.mp4
!!! Exception during processing !!!
Traceback (most recent call last):
  File "Z:\R3P0S\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\R3P0S\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\R3P0S\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\R3P0S\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\nodes\deforum_video_nodes.py", line 307, in fn
    self.save_video(full_output_folder, filename, counter, fps, audio, codec, format)
  File "Z:\R3P0S\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\nodes\deforum_video_nodes.py", line 437, in save_video
    del tmp_audio_file
        ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'tmp_audio_file' where it is not associated with a value

**Comment by XmYx** [comment]
pushed a fix!
