### ISSUE TITLE
No module named 'deforum.models'

### ISSUE THREAD

**Issue by huyunan496** [XmYx/deforum-comfy-nodes#25]
EXTENDING PATH WITH /opt/conda/lib/python3.10/site-packages/deforum/models/depth_models
Traceback (most recent call last):
  File "/data/app/ComfyUI/nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/app/ComfyUI/custom_nodes/deforum-comfy-nodes/__init__.py", line 8, in <module>
    from .deforum_nodes.mapping import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/data/app/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/mapping.py", line 16, in <module>
    from .nodes.deforum_cond_nodes import *
  File "/data/app/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/nodes/deforum_cond_nodes.py", line 5, in <module>
    from ..modules.deforum_ComfyUI/_helpers import blend_tensors, blend_methods
  File "/data/app/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/modules/deforum_ComfyUI/_helpers.py", line 14, in <module>
    from deforum.pipelines.deforum_animation.animation_helpers import DeforumAnimKeys
  File "/opt/conda/lib/python3.10/site-packages/deforum/__init__.py", line 12, in <module>
    from .generators import (ComfyDeforumGenerator,
  File "/opt/conda/lib/python3.10/site-packages/deforum/generators/__init__.py", line 2, in <module>
    from .film_interp_generator import FILMInterpolator
  File "/opt/conda/lib/python3.10/site-packages/deforum/generators/film_interp_generator.py", line 4, in <module>
    from ..models.FILM.inference import FilmModel
ModuleNotFoundError: No module named 'deforum.models'

Cannot import /data/app/ComfyUI/custom_nodes/deforum-comfy-nodes module for custom nodes: No module named 'deforum.models'
failed to load module /data/app/ComfyUI/custom_nodes/deforum-comfy-nodes

**Comment by XmYx** [comment]
PLease update the node package, and make sure that you remove 'deforum' pip package from the venv beforehand.
