### ISSUE TITLE
module 'jax.random' has no attribute 'KeyArray'

### ISSUE THREAD

**Issue by lanyan520** [XmYx/deforum-comfy-nodes#26]
error message:

Traceback (most recent call last):
  File "/Users/idea/ai_study/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/idea/ai_study/ComfyUI/custom_nodes/deforum-comfy-nodes/__init__.py", line 1, in <module>
    from .deforum_nodes.mapping import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Users/idea/ai_study/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/mapping.py", line 16, in <module>
    from .nodes.deforum_cond_nodes import *
  File "/Users/idea/ai_study/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/nodes/deforum_cond_nodes.py", line 5, in <module>
    from ..modules.deforum_comfyui_helpers import blend_tensors, blend_methods
  File "/Users/idea/ai_study/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/modules/deforum_comfyui_helpers.py", line 14, in <module>
    from deforum.pipelines.deforum_animation.animation_helpers import DeforumAnimKeys
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/deforum/__init__.py", line 1, in <module>
    from .typed_classes import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/deforum/typed_classes/__init__.py", line 2, in <module>
    from .generation_args import GenerationArgs
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/deforum/typed_classes/generation_args.py", line 38, in <module>
    from .schedulers import SchedulerType
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/deforum/typed_classes/schedulers.py", line 3, in <module>
    from diffusers.schedulers import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/diffusers/__init__.py", line 30, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/diffusers/pipelines/__init__.py", line 19, in <module>
    from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/diffusers/pipelines/auto_pipeline.py", line 20, in <module>
    from .controlnet import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/diffusers/pipelines/controlnet/__init__.py", line 16, in <module>
    from .pipeline_controlnet import StableDiffusionControlNetPipeline
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet.py", line 28, in <module>
    from ...models import AutoencoderKL, ControlNetModel, UNet2DConditionModel
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/diffusers/models/__init__.py", line 36, in <module>
    from .controlnet_flax import FlaxControlNetModel
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/diffusers/models/controlnet_flax.py", line 25, in <module>
    from .modeling_flax_utils import FlaxModelMixin
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/diffusers/models/modeling_flax_utils.py", line 46, in <module>
    class FlaxModelMixin(PushToHubMixin):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/diffusers/models/modeling_flax_utils.py", line 195, in FlaxModelMixin
    def init_weights(self, rng: jax.random.KeyArray) -> Dict:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jax/_src/deprecations.py", line 54, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'

Cannot import /Users/idea/ai_study/ComfyUI/custom_nodes/deforum-comfy-nodes module for custom nodes: module 'jax.random' has no attribute 'KeyArray'

How should I solve it？

**Comment by GeekyGhost** [comment]
wait, I can't remember if this was the error I got or not, I think I just went to manager, hit install packages and copy and pasted the name of the missing dependency and it installed it.
