### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by mandrewspicard** [XmYx/deforum-comfy-nodes#38]
Hey, been having an issue getting this to import properly, here's the main error section, I can get more if you want to see higher up the chain:

```
 Collecting matplotlib==3.7.1 (from deforum==0.1.8.dev1)
   Using cached matplotlib-3.7.1-cp311-cp311-win_amd64.whl.metadata (5.8 kB)
 Collecting pandas==1.5.3 (from deforum==0.1.8.dev1)
   Using cached pandas-1.5.3-cp311-cp311-win_amd64.whl.metadata (12 kB)
 Collecting av==10.0.0 (from deforum==0.1.8.dev1)
   Using cached av-10.0.0-cp311-cp311-win_amd64.whl.metadata (4.5 kB)
 Collecting pims==0.6.1 (from deforum==0.1.8.dev1)
   Using cached PIMS-0.6.1.tar.gz (86 kB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\micha\AppData\Local\Temp\pip-install-sthi0yu7\pims_d6cf94001c6b46c99c6dafd05c4a1ec0\setup.py", line 3, in <module>
[!]       import versioneer
[!]   ModuleNotFoundError: No module named 'versioneer'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
```

Any advice would be appreciated

**Comment by prakash54035** [comment]
same here. any solution?

**Comment by XmYx** [comment]
Hey! Checked, and due to some repo refactorings there was indeed a bug, please reinstall the nodes, and make sure to run pip uninstall deforum in your venv. If the issue persists, I suggest a clean installation of ComfyUI, additional custom node dependencies might break things still, but on a clean install, I've just tested, it works. My method is:
cloning Comfy then Comfy Manager, 
making a venv, 
installing Comfy requirements, 
then handle everything else in Comfy Manager once running, 
search for Deforum, 
install the official nodes, 
Restart Comfy, 
load example graph, (ComfyUI/custom_nodes/deforum-comfy-nodes/examples/deforum_base.json)
*refresh browser page!!!*, 
Queue Prompt.

**Comment by dancemanUK** [comment]
> 昨天安装并运行没有问题。今天更新了 comfyui 和这个扩展，并得到了同样的问题：
> 
> ![image](https://private-user-images.githubusercontent.com/1844512/339146286-7cd4f6e8-9c1f-4a4c-858a-b9beecce661d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NjY3MzcsIm5iZiI6MTcxODQ2NjQzNywicGF0aCI6Ii8xODQ0NTEyLzMzOTE0NjI4Ni03Y2Q0ZjZlOC05YzFmLTRhNGMtODU4YS1iOWJlZWNjZTY2MWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTVUMTU0NzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTJlZjRiNTU5OGYwNmRiMTg0MjQ3OTM5ODBjOGQwY2ZkNDgzM2E3MzgzNGFiNTAwZjliZWU3ZTM4NzU0MTUzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uxH3Qyn-bT5Z9OObUrMwM05QswA4dvJsseUio10HxC8)

ComfyUI\custom_nodes\deforum-comfy-nodes>..\..\..\python_embeded\python.exe -s -m pip install versioneer

Successfully installed versioneer-0.29

ComfyUI\custom_nodes\deforum-comfy-nodes>..\..\..\python_embeded\python.exe -s -m pip install pims==0.6.1
Successfully installed pims-0.6.1 slicerator-1.1.0

**Comment by alienufosoul** [comment]
![339949843-bb03f576-f7c1-490c-9c84-755c943aa9a9](https://github.com/XmYx/deforum-comfy-nodes/assets/17532290/34428a2b-e7e6-4219-ac34-020cd8589ee5)
Still Getting the same error, any help?

**Comment by XmYx** [comment]
Please press Try Fix in the manager, if that doesnt help, in the venv run: "pip uninstall deforum -y", then Try Fix/Reinstall the nodes, pushed an update to the backed to loosen pandas version requirement.

**Comment by show8888fire** [comment]
In my case, the following commands worked fine:

C:\ComfyUI-sub\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\python_embeded>python.exe -s -m pip install versioneer

C:\ComfyUI-sub\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\python_embeded>python.exe -s -m pip install pims==0.6.1

dancemanUK, Thank you!

**Comment by XmYx** [comment]
Thanks! Added in the requirements.txt!

**Comment by az1fr3** [comment]
Any help? (venv) D:\IA\SD\ComfyUI_Deforum\ComfyUI\custom_nodes\deforum-comfy-nodes>pip install -r requirements.txt
Collecting git+https://github.com/deforum-studio/deforum.git (from -r requirements.txt (line 16))
  Cloning https://github.com/deforum-studio/deforum.git to c:\users\56988\appdata\local\temp\pip-req-build-95ja1fms
  Running command git clone --filter=blob:none --quiet https://github.com/deforum-studio/deforum.git 'C:\Users\56988\AppData\Local\Temp\pip-req-build-95ja1fms'
  error: RPC failed; curl 18 HTTP/2 stream 3 was reset
  error: 8036 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output
  fatal: could not fetch e6ed6d4cfd773df1b489bb70aae0a67fbfd5d51a from promisor remote
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/deforum-studio/deforum.git 'C:\Users\56988\AppData\Local\Temp\pip-req-build-95ja1fms' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/deforum-studio/deforum.git 'C:\Users\56988\AppData\Local\Temp\pip-req-build-95ja1fms' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.1.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) D:\IA\SD\ComfyUI_Deforum\ComfyUI\custom_nodes\deforum-comfy-nodes>pip install -r requirements.txt --user
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

[notice] A new release of pip is available: 23.1.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) D:\IA\SD\ComfyUI_Deforum\ComfyUI\custom_nodes\deforum-comfy-nodes>

**Comment by XmYx** [comment]
Fixes were pushed to both the nodes and backend libs.

Please make sure to uninstall 'deforum', the underlying backend library ( https://github.com/XmYx/deforum-studio ), and that you reinstall the node package as well. A fix was pushed and tested on a fresh Comfy installation.
