### ISSUE TITLE
Error when I try to execute a deforum demo workflow.

### ISSUE THREAD

**Issue by razvanab** [XmYx/deforum-comfy-nodes#44]
ComfyUI-0246 appears in the log so I will try to disable it and see if that helps.

```
`Failed to validate prompt for output 172:
* (prompt):
  - Value not in list: seed_behavior: 'normal' not in ['fixed', 'random']
  - Value not in list: sampler_name: '25' not in (list of length 40)
  - Value not in list: scheduler: '7' not in ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform']
* DeforumBaseParamsNode 172:
  - Value not in list: seed_behavior: 'normal' not in ['fixed', 'random']
  - Value not in list: sampler_name: '25' not in (list of length 40)
  - Value not in list: scheduler: '7' not in ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform']
Output will be ignored
#135 [DeforumGetCachedLatentNode]: 0.00s
#181 [DeforumGetCachedImageNode]: 0.00s
#182 [DeforumGetCachedImageNode]: 0.00s
#186 [DeforumPromptNode]: 0.00s
#150 [DeforumAnimParamsNode]: 0.00s
#151 [DeforumDepthParamsNode]: 0.00s
#152 [DeforumTranslationParamsNode]: 0.00s
#155 [DeforumColorParamsNode]: 0.00s
#185 [DeforumCadenceParamsNode]: 0.00s
#172 [DeforumBaseParamsNode]: 0.00s
#154 [DeforumDiffusionParamsNode]: 0.00s
#157 [DeforumHybridScheduleNode]: 0.00s
#153 [DeforumNoiseParamsNode]: 0.00s
!!! Exception during processing!!! 'euler'
Traceback (most recent call last):
  File "H:\DEV\Conda\envs\comfy\Lib\site-packages\numexpr\necompiler.py", line 743, in getArguments
    a = local_dict[name]
        ~~~~~~~~~~^^^^^^
KeyError: 'euler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\DEV\Conda\envs\comfy\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\nodes\deforum_iteration_nodes.py", line 124, in get
    keys, prompt_series, areas = get_current_keys(anim_args, args.seed, root, area_prompts=deforum_data.get("area_prompts"))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\modules\deforum_comfyui_helpers.py", line 73, in get_current_keys
    keys = DeforumAnimKeys(anim_args, seed)  # if not use_parseq else ParseqAnimKeys(parseq_args, video_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\DEV\Conda\envs\comfy\Lib\site-packages\deforum\pipelines\deforum_animation\animation_helpers.py", line 1255, in __init__
    self.seed_schedule_series = self.fi.get_inbetweens(self.fi.parse_key_frames(anim_args.seed_schedule))
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\DEV\Conda\envs\comfy\Lib\site-packages\deforum\pipelines\deforum_animation\animation_helpers.py", line 1380, in parse_key_frames
    self.sanitize_value(frameParam[0].strip())) else int(numexpr.evaluate(
                                                         ^^^^^^^^^^^^^^^^^
  File "H:\DEV\Conda\envs\comfy\Lib\site-packages\numexpr\necompiler.py", line 819, in evaluate
    arguments = getArguments(names, local_dict, global_dict)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\DEV\Conda\envs\comfy\Lib\site-packages\numexpr\necompiler.py", line 745, in getArguments
    a = global_dict[name]
        ~~~~~~~~~~~^^^^^^
KeyError: 'euler'`
```

**Comment by 6sixteen** [comment]
same problem！Are example workflows obsolete？The Node has wrong parameters! QAQ
![0aacfc39b7ca8d2b029a2ae4a053041](https://github.com/XmYx/deforum-comfy-nodes/assets/26003677/0b3d13f5-a510-4e71-a605-b72fb00bd00d)

**Comment by XmYx** [comment]
Hey! After loading the workflow, please refresh the page, additionally, right click on the Base Parameters (and whichever node is erroring) and click Fix Node (recreate). This will ensure that your frontend picks up on the changes. I shall update the uploaded workflows to eliminate this issue.
