### ISSUE TITLE
Nodes Not listed

### ISSUE THREAD

**Issue by DavidWhocares** [XmYx/deforum-comfy-nodes#59]
I tried installing this through the manger and manually, ever time i pull an example workflow it says its missing the nodes. I have tried uninstalling and reinstalling but for whatever reason comfyui is acting like the nodes are not there.
![Screenshot (13)](https://github.com/user-attachments/assets/a4cf0720-1db9-44bd-b92b-3b09c1306daa)
![Screenshot (14)](https://github.com/user-attachments/assets/ea204448-271b-4d1e-b6d3-31df160d5182)

**Comment by Taisabe** [comment]
> Hi! Can you check, that during startup, when it tries to import the nodes, what the error message is? I'll also be checking it once I'm free from work.

Total VRAM 6144 MB, total RAM 32495 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\web
D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\blibla-comfyui-extensions\extensions
D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\web\extensions\failfast-comfyui-extensions
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2808 [69667290] *DETACHED | Released on '2024-11-04'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\__init__.py", line 1, in <module>
    from .deforum_nodes.mapping import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\mapping.py", line 13, in <module>
    from .nodes.deforum_audiosync_nodes import *
  File "D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\nodes\deforum_audiosync_nodes.py", line 8, in <module>
    from pydub import AudioSegment
ModuleNotFoundError: No module named 'pydub'

Cannot import D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes module for custom nodes: No module named 'pydub'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\blibla-comfyui-extensions
   0.3 seconds: D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable_nvidia (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes


like this) i have same problem ) great thanks

**Comment by DavidWhocares** [comment]
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-15 19:23:38.889209
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\Users\ ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\Users\ ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI
** Log path: D:\Users\ ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\comfyui.log
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-15 19:23:39.876965
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]

Total VRAM 24564 MB, total RAM 32509 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention

Traceback (most recent call last):
  File "D:\Users\ ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Users\ ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\__init__.py", line 1, in <module>
    from .deforum_nodes.mapping import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Users\ ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\mapping.py", line 13, in <module>
    from .nodes.deforum_audiosync_nodes import *
  File "D:\Users\ ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\nodes\deforum_audiosync_nodes.py", line 8, in <module>
    from pydub import AudioSegment
ModuleNotFoundError: No module named 'pydub'

Cannot import D:\Users\ ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes module for custom nodes: No module named 'pydub'

**Comment by danzeeeman** [comment]
I'm hitting the same issue

**Comment by XmYx** [comment]
I see. The issue is caused by comfy trying to use the --user flag when installing the requirements. I'll be able to check that in about 24hrs, to solve it, you can do a normal: "pip install pydub" in the venv, and if any other module would say, module not found, just do the same to it.

**Comment by danzeeeman** [comment]
yeah still hit issues @XmYx something else is going on

**Comment by f1tzcarrald0** [comment]
@XmYx same issue for me here. 
Have tried on multiple machines

**Comment by lunatico67** [comment]
> I see. The issue is caused by comfy trying to use the --user flag when installing the requirements. I'll be able to check that in about 24hrs, to solve it, you can do a normal: "pip install pydub" in the venv, and if any other module would say, module not found, just do the same to it.

Hi
Same problem here.  Does not work, import failed.
you can do a normal: "pip install pydub" in the venv    -How is it done?

**Comment by XmYx** [comment]
Please make sure to uninstall 'deforum', the underlying backend library ( https://github.com/XmYx/deforum-studio ), and that you reinstall the node package as well. A fix was pushed and tested on a fresh Comfy installation.

**Comment by valre2303** [comment]
This is happening to me again with everything updated and fresh nodes installed from nodes manager.
