### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.models.unet_2d_condition'

### ISSUE THREAD

**Issue by GamingDaveUk** [XmYx/deforum-comfy-nodes#60]
ModuleNotFoundError: No module named 'diffusers.models.unet_2d_condition'

This seems to be due to the fact the latest diffusers do not have this function, cant roll back the diffusers with out causining issues.
If the project is updated to the latest diffusers (if even possible) can i get a ping? Had to remove the package for now.

**Comment by le-si** [comment]
happens to me too

**Comment by XmYx** [comment]
Ill fix in the morning, till then, you can delete the diffusers nodes from ainodes_frontend/nodes. When updating make sure to run:

Git stash
Git pull

**Comment by DoctorDiffusion** [comment]
I am getting this same error with a fresh install from the ComfyUI Manager.

**Comment by dsigmabcn** [comment]
Still same issue. Some modules in diffusers are in different folders, but then then I reach to this error:

```
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/deforum-comfy-nodes/__init__.py", line 1, in <module>
    from .deforum_nodes.mapping import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/workspace/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/mapping.py", line 16, in <module>
    from .nodes.deforum_cond_nodes import *
  File "/workspace/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/nodes/deforum_cond_nodes.py", line 5, in <module>
    from ..modules.deforum_comfyui_helpers import blend_tensors, blend_methods
  File "/workspace/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/modules/deforum_comfyui_helpers.py", line 14, in <module>
    from deforum.pipelines.deforum_animation.animation_helpers import DeforumAnimKeys
ModuleNotFoundError: No module named 'deforum.pipelines.deforum_animation'
```

Which I cannot fix

**Comment by OColinWineO** [comment]
same question

**Comment by XmYx** [comment]
Please make sure to uninstall 'deforum', the underlying backend library ( https://github.com/XmYx/deforum-studio ), and that you reinstall the node package as well. A fix was pushed and tested on a fresh Comfy installation.
