### ISSUE TITLE
No module named 'deforum'

### ISSUE THREAD

**Issue by weisiren000** [XmYx/deforum-comfy-nodes#61]
Traceback (most recent call last):
  File "D:\.Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\.Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\__init__.py", line 1, in <module>
    from .deforum_nodes.mapping import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\.Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\mapping.py", line 16, in <module>
    from .nodes.deforum_cond_nodes import *
  File "D:\.Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\nodes\deforum_cond_nodes.py", line 5, in <module>
    from ..modules.deforum_comfyui_helpers import blend_tensors, blend_methods
  File "D:\.Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\modules\deforum_comfyui_helpers.py", line 14, in <module>
    from deforum.pipelines.deforum_animation.animation_helpers import DeforumAnimKeys
ModuleNotFoundError: No module named 'deforum'

Cannot import D:\.Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes module for custom nodes: No module named 'deforum'

Should I pip install the 'deforum' ?

**Comment by sunbeibei-hub** [comment]
i have it, too.

**Comment by lonrencn** [comment]
+1

**Comment by lonrencn** [comment]
if your conda env use python=3.12 then its this error
you need create env use python 3.11

**Comment by weisiren000** [comment]
谢谢大家，我尝试创建了独立的conda环境，管理了我本地的环境就成功的兼容了大部分的插件
